#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

OLD_HOME=$HOME
cd $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_REPO_DIR

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python site/manage.py migrate --noinput'"
python site/manage.py migrate --noinput

echo "Executing 'grunt build'"
npm install grunt-cli
grunt build

echo "Executing 'python site/manage.py collectstatic --noinput -i *.css.map -i *.scss'"
python site/manage.py collectstatic --noinput -i *.css.map -i *.scss

cd $HOME
export HOME=$OLD_HOME
