#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

cd $OPENSHIFT_REPO_DIR

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python site/manage.py migrate --noinput'"
python site/manage.py migrate --noinput

# # done with the collectstatic script instead
# echo "Executing 'python site/manage.py collectstatic --noinput -i *.css.map -i *.scss'"
# python site/manage.py collectstatic --noinput -i *.css.map -i *.scss

cd $HOME
