#!/bin/bash

echo "`date`: `cat $(dirname \"$0\")/chrono.dat`"

filename="worshipdb_backup_`date "+%m_%d_%Y"`.sql"

# back up mysql databases
mysqldump -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --all-databases  > ~/app-deployments/backup/$filename