#!/bin/bash

echo "`date`: `cat $(dirname \"$0\")/chrono.dat`"

# Adding FULLTEXT search to MySQL db
python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/addfulltext.py

# back up mysql databases
mysqldump -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --all-databases  > ~/app-root/data/mysql/worshipdb.sql