# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:14
from __future__ import unicode_literals

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('artist', models.CharField(max_length=50)),
                ('speed', models.CharField(choices=[(b'', b''), (b'F', b'Fast'), (b'S', b'Slow'), (b'FS', b'Fast/Slow')], max_length=2)),
                ('lyrics', models.TextField()),
                ('doc', models.FileField(upload_to=database.models.doc_upload_file, validators=[database.models.doc_file_validator])),
                ('pdf', models.FileField(upload_to=database.models.pdf_upload_file, validators=[database.models.pdf_file_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='themes',
            field=models.ManyToManyField(related_name='songs', to='database.Theme'),
        ),
    ]
