# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
