# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


def current_songs_already_posted(apps, schema_editor):
    Song = apps.get_model('database', 'Song')
    Song.objects.update(post_facebook=True)


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_unique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='post_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            current_songs_already_posted,
            migrations.RunPython.noop
        )
    ]
