#!/usr/bin/python

import sys, os
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'site'))

from site_settings import wsgi

# reuse the application callable from site.site_settings.wsgi
application = wsgi.application
